### ISSUE TITLE
Planning Center Integration doesn't import all items

### ISSUE THREAD

**Issue by CameronDevine** [TheoTech/spf.io#3] opened 2018-06-12 01:11 UTC
When using the planning center integration, only the first 12-13 items are imported.

**Comment by chrislim** [comment] 2018-06-12 02:06
By default the playlist import feature ignores "header" items in planning center. The next release will include a checkbox so you can import header items too.

**Comment by CameronDevine** [comment] 2018-06-12 06:45
I just attempted to import the plan for this Sunday. The import got as far as the Doxology. Is this the current expected behavior?

![image](https://user-images.githubusercontent.com/10394896/41274051-cfbf1e84-6dd0-11e8-9d77-5fdf97fe298a.png)

**Comment by chrislim** [comment] 2018-06-13 06:45
We just pushed a release (10 minutes ago) that includes the checkbox to include header items. Please give it a try now with that option enabled.

**Comment by CameronDevine** [comment] 2018-06-13 17:39
Doing the import again with the include headers switch on causes the grey bars to appear in the plan as well as the white items.

![image](https://user-images.githubusercontent.com/10394896/41367959-5c8f7500-6ef5-11e8-88d6-f89783397eb0.png)

Reviewing the image in my last comment it is the expected behavior that both the header named Doxology and the item named Doxology are both imported.

![image](https://user-images.githubusercontent.com/10394896/41368088-b8091918-6ef5-11e8-817c-0323a7730fb4.png)

However the import still stops at the Doxology.

**Comment by chrislim** [comment] 2018-06-13 17:51
Ah I see. The issue is paging. Each page of items has 25 results and your playlist has 32. We need to follow links to get every page of items to solve this problem.

**Comment by CameronDevine** [comment] 2018-06-13 18:08
It also looks like you could also increase the maximum number of items returned from 25 up to 100.

http://planningcenter.github.io/api-docs/#items

This would probably fix the problem for all but a few extremely long or complex services.

**Comment by chrislim** [comment] 2018-06-13 18:30
Yea, that's a good idea. We can also go through all pages and collate the results. Won't be able to do another release for this Sunday, but hopefully we can ship the solution by the one after.

**Comment by chrislim** [comment] 2018-06-30 02:37
Resolved in recent release.

**Closed as completed by chrislim** 2018-06-30 02:37 UTC
Labels: enhancement
